[package]
name = "hfst"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
hfst-types = { workspace = true }
hfst-core = { workspace = true }
hfst-openfst = { workspace = true }
hfst-ol = { workspace = true }
glob = "0.3"
icu = "2.2.0"
nfst-xre = { workspace = true }
nfst-lexc = { workspace = true }
nfst-pmatch = { workspace = true }
nfst-twolc = { workspace = true }
nfst-xfst = { workspace = true }
thiserror = "2.0.18"
tracing = "0.1.44"
