[package]
name = "hfst"
version = "0.1.0"
edition = "2024"

#[lib]
#crate-type = ["lib", "staticlib"]

[build-dependencies]
cc = "1.0.79"
cmake = "=0.1.48"
pkg-config = "0.3.27"
vcpkg = "0.2.15"

[dependencies]
libc = "0.2.153"
