//! Port of 'libhfst/src/HfstExceptionDefs.{h,cc}' — the HFST exception
//! hierarchy.
//!
//! C++ exceptions become Rust structs; 'throw' becomes ['std::panic::panic_any']
//! carrying the typed exception as the panic payload (a 'catch (const E&)' then
//! ports to 'std::panic::catch_unwind' + downcast), preserving HFST's exact
//! throw/catch control flow. C++ subclassing is modelled by composition: each
//! child holds an ['HfstException'] 'base', generated by the
//! ['hfst_exception_child!'] macro that mirrors 'HFST_EXCEPTION_CHILD_*'.

use std::sync::Mutex;

use crate::hfst_data_types::ImplementationType;

// 'std::string hfst_exception;' — a file-scope global, default empty.
static HFST_EXCEPTION: Mutex<String> = Mutex::new(String::new());

// [spec:hfst:def:hfst-exception-defs.hfst-set-exception-fn]
// [spec:hfst:sem:hfst-exception-defs.hfst-set-exception-fn]
pub fn hfst_set_exception(name: String) {
    *HFST_EXCEPTION.lock().unwrap() = name;
}

// [spec:hfst:def:hfst-exception-defs.hfst-get-exception-fn]
// [spec:hfst:sem:hfst-exception-defs.hfst-get-exception-fn]
pub fn hfst_get_exception() -> String {
    HFST_EXCEPTION.lock().unwrap().clone()
}

/// \brief Base class for HfstExceptions. Holds its own name and the file and
/// line number where it was thrown.
// [spec:hfst:def:hfst-exception-defs.hfst-exception]
#[derive(Clone, Debug)]
pub struct HfstException {
    pub name: String,
    pub file: String,
    pub line: usize,
}

impl HfstException {
    // The default constructor 'HfstException(void)' leaves the members
    // default-initialised; in C++ 'line' is then indeterminate, here it is 0.
    pub fn new_default() -> Self {
        HfstException {
            name: String::new(),
            file: String::new(),
            line: 0,
        }
    }

    // [spec:hfst:def:hfst-exception-defs.hfst-exception.hfst-exception-fn]
    // [spec:hfst:sem:hfst-exception-defs.hfst-exception.hfst-exception-fn]
    pub fn new(name: String, file: String, line: usize) -> Self {
        HfstException { name, file, line }
    }

    // [spec:hfst:def:hfst-exception-defs.hfst-exception.operator-fn]
    // [spec:hfst:sem:hfst-exception-defs.hfst-exception.operator-fn]
    //
    // 'std::string operator()(void) const' — Rust has no call-operator
    // overloading on inherent methods, so this is named 'call'.
    pub fn call(&self) -> String {
        format!(
            "Exception: {} in file: {} on line: {}",
            self.name, self.file, self.line
        )
    }

    // [spec:hfst:def:hfst-exception-defs.hfst-exception.what-fn]
    // [spec:hfst:sem:hfst-exception-defs.hfst-exception.what-fn]
    pub fn what(&self) -> String {
        format!(
            "Exception: {} in file: {} on line: {}",
            self.name, self.file, self.line
        )
    }
}

/// \brief Macro to throw an exception of type @a E.
///
/// Ports 'HFST_THROW(E)': set the global exception name, then panic carrying a
/// freshly-constructed 'E' (with '#E', file and line).
#[macro_export]
macro_rules! HFST_THROW {
    ($e:ident) => {{
        $crate::hfst_exception_defs::hfst_set_exception(stringify!($e).to_string());
        // No trailing ';': the block is '!'-typed so callers' '?'-free control
        // flow (e.g. a throw as a function's tail) type-checks.
        std::panic::panic_any($e::new(
            stringify!($e).to_string(),
            file!().to_string(),
            line!() as usize,
        ))
    }};
}

/// \brief Macro to throw an exception of type @a E with message @a M.
///
/// Ports 'HFST_THROW_MESSAGE(E, M)': the constructed name is '"E: M"'.
#[macro_export]
macro_rules! HFST_THROW_MESSAGE {
    ($e:ident, $m:expr) => {{
        $crate::hfst_exception_defs::hfst_set_exception(stringify!($e).to_string());
        let __name = format!("{}: {}", stringify!($e), $m);
        // No trailing ';': see HFST_THROW.
        std::panic::panic_any($e::new(__name, file!().to_string(), line!() as usize))
    }};
}

/// \brief Declare and define a subclass of @a HfstException of type @a CHILD.
///
/// Ports the pair 'HFST_EXCEPTION_CHILD_DECLARATION' /
/// 'HFST_EXCEPTION_CHILD_DEFINITION': an empty subclass whose constructor
/// forwards '(name, file, line)' to the base.
macro_rules! hfst_exception_child {
    ($name:ident) => {
        #[derive(Clone, Debug)]
        pub struct $name {
            pub base: HfstException,
        }

        impl $name {
            pub fn new(name: String, file: String, line: usize) -> Self {
                $name {
                    base: HfstException::new(name, file, line),
                }
            }
        }
    };
}

hfst_exception_child!(HfstTransducerTypeMismatchException);

/// \brief The library required by the implementation type requested is not
/// linked to HFST.
// [spec:hfst:def:hfst-exception-defs.implementation-type-not-available-exception]
#[derive(Clone, Debug)]
pub struct ImplementationTypeNotAvailableException {
    pub base: HfstException,
    // C++ field name is 'type', which is a Rust keyword; ported as 'type_'.
    type_: ImplementationType,
}

impl ImplementationTypeNotAvailableException {
    // [spec:hfst:def:hfst-exception-defs.implementation-type-not-available-exception.implementation-type-not-available-exception-fn]
    // [spec:hfst:sem:hfst-exception-defs.implementation-type-not-available-exception.implementation-type-not-available-exception-fn]
    pub fn new(name: String, file: String, line: usize, type_: ImplementationType) -> Self {
        ImplementationTypeNotAvailableException {
            base: HfstException::new(name, file, line),
            type_,
        }
    }

    // [spec:hfst:def:hfst-exception-defs.implementation-type-not-available-exception.get-type-fn]
    // [spec:hfst:sem:hfst-exception-defs.implementation-type-not-available-exception.get-type-fn]
    pub fn get_type(&self) -> ImplementationType {
        self.type_
    }
}

hfst_exception_child!(FunctionNotImplementedException);
hfst_exception_child!(StreamNotReadableException);
hfst_exception_child!(StreamCannotBeWrittenException);
hfst_exception_child!(StreamIsClosedException);
hfst_exception_child!(EndOfStreamException);
hfst_exception_child!(TransducerIsCyclicException);
hfst_exception_child!(NotTransducerStreamException);
hfst_exception_child!(FileIsInGZFormatException);
hfst_exception_child!(NotValidAttFormatException);
hfst_exception_child!(NotValidPrologFormatException);
hfst_exception_child!(NotValidLexcFormatException);
hfst_exception_child!(StateIsNotFinalException);
hfst_exception_child!(ContextTransducersAreNotAutomataException);
hfst_exception_child!(TransducersAreNotAutomataException);
hfst_exception_child!(TransducerIsNotAutomatonException);
hfst_exception_child!(StateIndexOutOfBoundsException);
hfst_exception_child!(TransducerHeaderException);
hfst_exception_child!(MissingOpenFstInputSymbolTableException);
hfst_exception_child!(TransducerTypeMismatchException);
hfst_exception_child!(EmptySetOfContextsException);
hfst_exception_child!(SpecifiedTypeRequiredException);
hfst_exception_child!(HfstFatalException);
hfst_exception_child!(TransducerHasWrongTypeException);
hfst_exception_child!(IncorrectUtf8CodingException);
hfst_exception_child!(EmptyStringException);
hfst_exception_child!(SymbolNotFoundException);
hfst_exception_child!(MetadataException);
hfst_exception_child!(FlagDiacriticsAreNotIdentitiesException);
